title: "Saad Irfan"
email: mrsaadirfan@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  ğŸš€ JavaScript developer getting a Bachelorâ€™s degree in Computer Sciences from the University of Engineering & Technology. ğŸ¼ An MLH â€™20 fellow, ğŸ‘¨ğŸ»â€ğŸ’» Jr. Dev Advocate @Worwox, ğŸ’¥ an open-sourcer (authored several open-source tools), ğŸ¦‰open-source contributor (contributed to the likes of Node.js, Fluid Project, Global Public Inclusive Infrastructure), ğŸ™Œ former Googleâ€™s Developer Student Clubs Lead, ğŸ’» Beta â€“ Microsoft Learn Student Ambassador, âœï¸ Technical Writer, ğŸ—£ Speaker, and ğŸ¸ a Guitarist.
baseurl: "/"
url: "/portfolio"
twitter_username: msaaddev
github_username:  msaaddev

sass:
  sass_dir: _sass

icon: ./assets/img/icon.jpg
